export { default as Posts } from './Posts'
export { default as Login } from './Login'
export { default as Register } from './Register2'
export { default as Header } from './Header'
export { default as CreatePost } from './CreatePost'
